CREATE DATABASE rest;

CREATE TABLE IF NOT EXISTS rest.users (
    id INTEGER AUTO_INCREMENT,
    username VARCHAR(60) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);